version: "3"
services:
  jekins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "./volumes/jenkins:/var/jenkins_home"
  gogs-db:
    image: mysql
    container_name: gogs-db
    volumes:
      - "./volumes/gogs-db-mysql:/var/lib/mysql"
      - "./volumes/gogs-db-conf.d:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "gogs"
      MYSQL_USER: "gogs"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  gogs:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - "./volumes/gogs:/data"
  consul:
    image: consul
    container_name: consul
    volumes:
      - "./volumes/consul:/etc/consul.d"
