version: "3"

networks:
  cees:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         
services:
  jekins:
    image: jenkins/jenkins
    container_name: jenkins
    networks:
      cees:
    ports:
      - "50000:50000"
      # - "8080:8080"
    volumes:
      - "./volumes/host/:/host/"
      - "./volumes/jenkins:/var/jenkins_home"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      # - JENKINS_OPTS="--webroot=/var/cache/jenkins/war --prefix=/jenkins"
    # command:
    #   # /bin/bash -c "cp /host/jenkins /etc/default/jenkins && chmod 777 /etc/default/jenkins && /bin/tini -- /usr/local/bin/jenkins.sh"
    #   /bin/bash -c "/bin/tini -- /usr/local/bin/jenkins.sh"
  gogs-mysql-db:
    image: mysql:5.7
    container_name: gogs-mysql-db
    volumes:
      - "./volumes/gogs-db-mysql/:/var/lib/mysql/"
      - "./volumes/gogs-db-conf.d/:/etc/mysql/conf.d/"
    networks:
      cees:
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "gogs"
      MYSQL_USER: "gogs"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  gogs:
    image: gogs/gogs
    container_name: gogs
    networks:
      cees:
    ports:
      - "10022:22"
      # - "8081:3000"
    volumes:
      - "./volumes/gogs/:/data/"
      - "./volumes/host/:/host/"
    command:
      /bin/bash -c "cp /host/gogs.app.ini /data/gogs/conf/app.ini && /bin/s6-svscan /app/gogs/docker/s6/"
  xwiki:
    image: "xwiki:mysql-tomcat"
    container_name: xwiki
    networks:
      cees:
    depends_on:
      - xwiki-mysql-db
    # ports:
    #   - "8082:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=xwiki-mysql-db
    volumes:
      - ./volumes/xwiki/xwiki-data:/usr/local/xwiki
      - ./volumes/host/:/host/
    entrypoint:
      /host/xwiki-entrypoint.sh
  xwiki-mysql-db:
    image: "mysql:5.7"
    container_name: xwiki-mysql-db
    networks:
      cees:
    volumes:
      - "./volumes/xwiki-db-mysql/:/var/lib/mysql/"
      - "./volumes/xwiki-db-conf.d/:/etc/mysql/conf.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
  askbot:
    image: zout84/askbot-docker
    container_name: askbot
    networks:
      cees:
        ipv4_address: 10.5.0.104
    ports:
      - "8084:80"
    volumes:
      - "./volumes/host/:/host/"
    environment:
      - ASKBOT_ROOT=askbot/
      - ASKBOT_DB_HOST=askbot-postgres-db
      - ASKBOT_DB_PORT=5432
      - ASKBOT_DB_TYPE=postgresql_psycopg2
      - ASKBOT_DB_USERNAME=postgres
      - ASKBOT_DB_PASSWORD=password
    entrypoint:
      "/host/askbot.sh"
  askbot-postgres-db:
    image: postgres
    container_name: askbot-postgres-db
    networks:
      cees:
    # ports:
    #   - "5432:5432"
    volumes:
      - "./volumes/host/:/host/"
    environment:
      POSTGRES_DB: askbot
      POSTGRES_PASSWORD: password
  nginx:
    image: nginx
    container_name: nginx
    networks:
      cees:
    ports:
      - "80:80"
    volumes:
      - "./volumes/host/:/host/"
      # - "./volumes/nginx/html/:/usr/share/nginx/html:ro"
    command:
      /bin/bash -c "/host/wait-for-it.sh askbot:80; /host/wait-for-it.sh gogs:3000; /host/wait-for-it.sh jenkins:8080; /host/wait-for-it.sh xwiki:8080; cp /host/nginx.conf /etc/nginx/; nginx -g 'daemon off;'"
      # /bin/bash -c "/host/wait-for-it.sh askbot:80; cp /host/nginx.conf /etc/nginx/; nginx -g 'daemon off;'"
      # /bin/bash -c "nginx -g 'daemon off;'"
