version: "3"
services:
  # jekins:
  #   image: jenkins/jenkins
  #   container_name: jenkins
  #   ports:
  #     - "50000:50000"
  #     - "8080:8080"
  #   volumes:
  #     - "./volumes/host/:/host/"
  #     - "./volumes/jenkins:/var/jenkins_home"
  #   environment:
  #     - JENKINS_OPTS="--prefix=/jenkins"
  #     # - JENKINS_OPTS="--webroot=/var/cache/jenkins/war --prefix=/jenkins"
  #   # command:
  #   #   # /bin/bash -c "cp /host/jenkins /etc/default/jenkins && chmod 777 /etc/default/jenkins && /bin/tini -- /usr/local/bin/jenkins.sh"
  #   #   /bin/bash -c "/bin/tini -- /usr/local/bin/jenkins.sh"
  gogs-db:
    image: mysql
    container_name: gogs-db
    volumes:
      - "./volumes/gogs-db-mysql:/var/lib/mysql"
      - "./volumes/gogs-db-conf.d:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "gogs"
      MYSQL_USER: "gogs"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  gogs:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - "./volumes/gogs:/data"
     #    /data/gogs/conf
     # command="/gopath/src/github.com/gogits/gogs/gogs serv key-1 --config='/data/gogs/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAA....
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./volumes/host/:/host/"
      # - "./volumes/nginx/html/:/usr/share/nginx/html:ro"
    command:
      /bin/bash -c "cp /host/nginx.conf /etc/nginx/ && nginx -g 'daemon off;'"
      # /bin/bash -c "nginx -g 'daemon off;'"
